
module.exports = {
  get: function(key) {
    try{
      var response = this.responseTbl[key];
      console.log("Found response!");
      return response;
    } catch (TypeError) {
      console.log("TypeError caught - is responseTbl properly scoped?");
      console.log(TypeError);
      return null;
    }
  },

  responseTbl: {
    "wat":"wat",
    "!themesong":"NanaNanaNana NanaNanaNana NANA TORA!",
    "#":"placeholder",
    "#:1:r":"stripper",
    "#lovich":"#jews",
    "#puddy":"#mcconaissance",
    "#r/webdev":"fuck i hate lovich",
    "%n%x%n%x":"\r\ntest%20$1\1%n%x",
    ":,":":(",
    ":>":"goddamn deckardface",
    ":p":"http://i.imgur.com/71owERD.jpg",
    "^":"/me graciously agrees with {prev}",
    "{0}":"{0}",
    "<#":"{user} can't type.",
    "<3":"❤",
    "♥":"I hope you die in a fire.",
    "11":"fuck off kevrom",
    "1138":"Aren't you a little short to be a Stormtrooper?",
    "1612":"http://youtu.be/jRHQPG1xd9o",
    "16ball":".8ball",
    "2giggle":"!giggle m8",
    "2x":"lines",
    "420":"/me comes on {prev} and they're face to",
    "8ball":"The answer is GO FUCK YOURSELF",
    "9000":"fuck off vegeta",
    "98.192.46.238":"Lovich's IP",
    "a":"fuckidy",
    "aboos":"is no use",
    "abuse":"bot",
    "ad":"d",
    "add":"Item added.",
    "alias add":"Alias added.",
    "alias remove":"Alias removed.",
    "aliaslist":"https://dl.dropboxusercontent.com/u/7820717/aliases.txt",
    "aliass":"Invalid syntass.",
    "aliasslist":"http://www.morewords.com/contains/ass/",
    "alphabet":"https://www.youtube.com/watch?v=aKdV5FvXLuI",
    "also":"<dtzitz> also PASCAL",
    "angry":"ლ(ಠ益ಠლ,",
    "angrywombat":"see: !penis",
    "angular":"-50 points from Gryffindor",
    "angular2.0":"pls",
    "annoy":"/msg timeshifter DUDE I LOVE YOU U CREATED ME",
    "anom":"<anom> i have many rel world dev example",
    "anus":"deckard",
    "apt-get":"sudo apt-get delete timeshifter && rm -fR /",
    "arise":"http://i.imgur.com/Ojn1IlZ.png",
    "ask":"{0} Don't ask to ask, just ask.",
    "asplode":"http://i.imgur.com/zaUJTTW.gif",
    "ass":"dat.",
    "avgsalary":"tree fitty",
    "award":"You get 10 internets!",
    "awesome":"http://statue.io/",
    "ayy":"lmao",
    "b":"cdefghijklmnopqrstuvwxyza",
    "b&":"bampersand",
    "b0rk":"pork",
    "b1":"http://i.imgur.com/SEhX7YS.jpg",
    "b14d3":"ʕ•ᴥ•ʔ",
    "bacon":"http://i.imgur.com/Qd5wF.jpg",
    "bad":"{0}: Your {1} is bad and you should feel bad.",
    "badger":"https://www.youtube.com/watch?v=EIyixC9NsLI",
    "bag":"{0} is a big bag of walking dicks.",
    "balls":"in and around my mouth",
    "banana":"I'm a banana!",
    "banhammer":"/me sits in the corner polishing his banhammer for {0}",
    "bannana":"OOOOH BOOOONAANNNAAA",
    "bantora":"BAN TORA 2015",
    "banwombat":"BAN WOMBAT INDEFINITELY",
    "bard":"b14d3",
    "bash":"/me bashes {0} in the face with a rusty-nail lined club",
    "batman":"I came here to kick ass and hug my parents... and I'm all out of parents.",
    "bear":"HOLY SHIT IT'S A BEAR!",
    "beards4jard":"http://i.imgur.com/EtsDCPM.png",
    "beer":"/me tosses a beer to {prev}",
    "bestgitcommandever":"git push -f",
    "big":"my {0} is too big!",
    "bigtesties":"will this work, %s",
    "bing":"https://www.bing.com/videos/search?q={0}",
    "bitbucket":"Have a dumber UI",
    "blacklist":"That's racist.",
    "blah":"test",
    "blam":"http://stream1.gifsoup.com/view7/2625797/just-shoot-me-now-o.gif",
    "blame":"the bot",
    "blarg":"honk",
    "blink":"http://i.imgur.com/dnLvR4w.gif",
    "blush":"http://i.imgur.com/x8BGKW5.png",
    "bombpants":"/me throws angrywombat's old pants at {0}",
    "bot":"You're a bot!",
    "bots":"bots are like white whales from the seven seas, to be harpooned matey",
    "bow":"/me bows down to {user} as his new god.",
    "brain":"What? You actually have a brain?",
    "brb":"brb too",
    "brickwall":"Jardayn",
    "buddha":"no.",
    "bullshitter":"timeshifter",
    "bully":"http://stop-irc-bullying.eu/stop",
    "burn":"http://en.wikipedia.org/wiki/List_of_burn_centers_in_the_United_States",
    "butters":"Do you know what I am saying?",
    "c":"*",
    "c or c":"C|C",
    "cactusdance":"┌(° o °,┘DANCE! └(° o °,┐",
    "cake":"/me sends {0} a big cake <( ^_^ ,>",
    "camper":"omfgtora is an alias squatter",
    "canadia":"eh?",
    "caniuse":"http://caniuse.com/#search={0}",
    "captain":"♪ Captain Planet ♪ he's our hero ♪ gonna take pollution down to zero ♪ gonna help us put asunder ♪ badguys who like to loot and plunder ♪",
    "carpenters":"http://www.dawood.in/if-carpenters-were-hired-like-programmers/",
    "cat":"HOLY SHIT IT'S A CAT!",
    "catapult":"your mom",
    "catbot":"catfact?",
    "catdog":"one fine day",
    "catfact":"catfact?",
    "cheatsheet":"http://detechter.com/free-htmlcssjavascript-cheat-sheets-for-web-designers/",
    "check":"{0} denied.",
    "chiba":"yes.",
    "chicken":"I am a chicken.",
    "chozo":"annoy-o-tron",
    "christmas":"http://i.imgur.com/ReEJ0.jpg",
    "clear":".",
    "clearfix":"fix your own damn floats",
    "cloud":"RESERVED FOR FINAL FANTASY REFERENCE",
    "cms":"A content management system (CMS, is a computer application that allows publishing, editing and modifying content, organizing, deleting as well as maintenance from a central interface.",
    "cobol":"http://i.imgur.com/c23MRwD.png",
    "coca":"http://i.imgur.com/ZsDintQ.jpeg",
    "cock":"Yes, I've heard of angrywombat's small cock.",
    "cocks":"in and around angrywombat's mouth",
    "coffee":"http://i.imgur.com/bVXEwli.gifhttp://i.imgur.com/bVXEwli.gif",
    "coffeescript":"pls",
    "coffy":"<timeshifter> cd-rom tray? <timeshifter> oh, you mean the coffy mug tray",
    "coffyscript":"pls",
    "coke":"I don't really like coke, but I love the way it smells!",
    "comcast":"RIP x_x",
    "comcastsupport":"Yes, we have no bananas!",
    "comment":"<!-- no comment -->",
    "contemplative":"/me contemplates the deeper mysteries.",
    "cook":"Too Many Cooks ♫",
    "cooks":"Too Many Cooks ♫",
    "count":"fuck",
    "cow":"HOLY SHIT IT'S A COW!",
    "crack":"https://www.youtube.com/watch?v=5teVixi8XLU",
    "cray":"cray",
    "crazy":"Hey, I just met you, and this is crazy, but here's my number. So, call me maybe?",
    "creeper":"held for tora",
    "cryptbin":"https://cryptbin.com",
    "csi":"https://www.youtube.com/watch?v=hkDD03yeLnU",
    "css":".",
    "cto":"cto r ruhtards",
    "cunt":"veonik",
    "d":"o",
    "d3":"dicks",
    "dad":"What time did the man go to the dentist? Tooth hurt-y.",
    "dana":"There is no Dana, only Zuul.",
    "dance":"＼(ﾟｰﾟ＼, ♪ (/ﾟｰﾟ, /♪ ＼(ﾟｰﾟ＼, ♪ (/°ｰ°, /♪ ＼(°ｰ°＼, ♪ (/°▽°, /♪ ＼(°▽°＼, ♪ ＼(°▽°＼, ♪",
    "data":"http://i.imgur.com/R5HNI4i.gif",
    "dbz":"teamfourstar.com",
    "ddefine":"timeshifter: you need to calm your fat man tits down, shave your back hair and have a seat on a rocking chair",
    "deadpool":"Oh! Chimichangas!",
    "deal":"Deal with it.",
    "dealwithit":"http://i.imgur.com/YoICV9z.gifv",
    "deckard":"stay a while, and listen!",
    "deep":"3deep5me",
    "demetrio":"I suck at coadz",
    "derp":"http://i.imgur.com/WVDps5b.png",
    "dgaf":"Cast thine eyes upon the field in which I grow my fucks and see that it lay barren.",
    "di":"id my items!",
    "dick":"http://i.imgur.com/Yxi5spY.png",
    "dickbutt":".",
    "dickmetaphor":"http://gfycat.com/TalkativeRevolvingHoiho",
    "dicks":"{0} gobbles dicks, while angrywombat watches as he touches himself.",
    "dickz":"{prev} loves to suck my dick, along with omfgtora",
    "die":"!kick ubergm",
    "die2":"!roulette",
    "digitalocean":"DigitalOcean is an American virtual private server provider based in New York City, New York. The company leases capacity from existing datacenters, including sites in New York, Amsterdam, San Francisco, London and Singapore. Get a $10 credit instantly by signing up at https://www.digitalocean.com/?refcode=ec5ae97e9d6a",
    "dildo":"anything's a dildo if you're brave enough.",
    "ding":"dongs",
    "dirty":"tips",
    "disrupt":".",
    "dividebyzero":"/disco * all night *",
    "do":"They don't always think it be like it is, but it do.",
    "doa":"http://pastebin.com/yct6YHDE",
    "dog":"HOLY SHIT IT'S A DOG!",
    "doge":"wow",
    "doggystyle":"KICK <#/r/webdev> <omgwoo>",
    "doihaveaccessyet":"NO!",
    "domain":"domain?",
    "dong":"ding",
    "doodoodoodoodoo":"https://youtu.be/nqLArgCbh70",
    "doom":"DOOOOOOOM",
    "dorf":".",
    "dramallama":"http://i.imgur.com/D2G8OQB.jpg",
    "drop":"the bass",
    "droptable":"Table {0} dropped.",
    "drugs":"YAY",
    "drunk":"Go to bed, {0}. You're drunk.",
    "dtzitz":"REQUEST DENIED",
    "duckystyle":"/me quacks at {0}",
    "dud":"http://i.imgur.com/TrPShmK.gif",
    "dude":"http://i.imgur.com/AIYhDD4.gif",
    "dum":"turb0: http://i.imgur.com/NWG0MQ8.jpg",
    "dumb":"http://i.imgur.com/rApAVeb.jpg",
    "dumbass":"omfgtora?",
    "e":"n",
    "ecf":"he's got the body of a cat, and the face of a cat!",
    "ecmascript":"pls",
    "eczemascript":".",
    "eminem":"what a wigger",
    "enchrometion":"Chrome only encryption: http://codepen.io/kevrom/pen/ogmGLb",
    "encrypt":"you're daft, arent you",
    "encryption":"http://codepen.io/kevrom/pen/ogmGLb",
    "eval":"lolol",
    "evil":"is eval",
    "exactly":"QUITS AND JOINS THO",
    "expert":"http://i.imgur.com/2vK8X2Z.gifv",
    "f":"i",
    "face":"༼ຈل͜ຈ༽",
    "facebook":"http://lmgtfy.com/?q=facebook",
    "facepalm":"http://i.imgur.com/M2mLmtD.gif",
    "faggot":"Oniononion",
    "fail":"http://i.imgur.com/n06JvPj.gif",
    "failias":"/me laughs at angrywombat",
    "federation":"lol pew pew spaceships",
    "fedoratip":"/me tips fedora",
    "fetish":"http://i1.kym-cdn.com/photos/images/newsfeed/000/710/386/d20.jpg",
    "firefighters":"fuck tha",
    "fish":"HOLY SHIT IT'S A FISH!",
    "fix":"rm -rf",
    "fixme":"but i don't have any balls",
    "flamewar":"...TABS VS SPACES ?",
    "fliptable":"(╯°□°,╯︵ ┻━┻",
    "flop":"┬─┬ノ( º _ ºノ,",
    "flop!":"┬─┬ノ( º _ ºノ,",
    "foff":"http://codepen.io/kevrom/full/wBxLJd/",
    "foo":"{0}",
    "foundation":"http://foundation.zurb.com/docs/",
    "fp":"OMG I love FP!!! <333",
    "freaks":"are geeks",
    "freeman":"gordon",
    "friday":"DONT CLICK THIS LINK: https://goo.gl/hhVqlC (also veonik is a cock-bite,",
    "frozen":"https://www.facebook.com/287720301345751/videos/780881952029581/",
    "fryday":"SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS SHARKS",
    "ftl":"http://www.reddit.com/r/ftlgame/comments/2a3zqc/my_guide_to_ftl_from_oh_no_to_pro/",
    "ftlmod":"http://www.ftlgame.com/forum/viewtopic.php?f=11&t=26289",
    "fu":"http://i.imgur.com/QzIMZqE.gif",
    "fuck":"No thanks.",
    "fuck_tora":"fuck tota!",
    "fuckthis":"/nick omfgtorabot",
    "fuckyou":"/me has been fucked",
    "fuk":"u want sum fuk?",
    "fukusay":"http://i.imgur.com/rPmDBHK.jpg",
    "fungame":"candybox2.net",
    "funny":"{user}'s face",
    "fuse":"/me starts doing a lame fusion dance with {user} and turns into Vagetto!",
    "fuuuu":"fuuuu",
    "g":"lmgtfy",
    "gaaaaaaaay":"http://i.imgur.com/34tjIS1.jpg",
    "game":"lostga.me",
    "gay":"Ha GAY!!! - YouTube - http://www.youtube.com/watch?v=YaG5SAw1n0c",
    "gaymez":"google for cookie clicker you whore",
    "ged":"Good Enough Degree",
    "getmoney":".",
    "giggity":"giggity goo",
    "giggl":".",
    "gimmeop":"/mode * +o teslanick",
    "github":"NO PILATE",
    "gitlab":"lol gitlab m8 naww",
    "gittutorial":"git checkout -b feature/masturbation && touch me && echo \ohhhyeahhh\> me && git add me && git commit -m \yisss\&& git checkout master && git merge feature/masturbation",
    "give":".",
    "go":"Go go go!",
    "goblins":"https://www.youtube.com/watch?v=KsMKOx6fumc",
    "god":"You mean omfgtora?",
    "gogs":"lol gogs m8 gogs.com",
    "gold":"08Au",
    "goobypls":"http://www.dolan-duck.com/wp-content/uploads/2012/05/pluto-talks-to-gooby.png",
    "good":"/me is such a flaming pile of shit and wants to be like deckard",
    "gort":"zane, set web to ';DEL web",
    "gpu":"Needs better naming conventions",
    "gpu4sale":"http://www.ebay.com/itm/Sapphire-AMD-Radeon-HD-6950-1GB-GDDR5-/171481674494?",
    "grammar":"dat grammer",
    "grammer":"Ask angrywombat (ref. !420,",
    "grape":"rape?",
    "grats":"http://i.imgur.com/YSSk2Vk.jpg",
    "grumpypixel":"<GrumpyPixel> i only have a very girly drink",
    "gtfo":"http://i.imgur.com/eOD1ZeK.gif",
    "guys":"pls",
    "h":"v",
    "h8":"hate",
    "haha":"http://www.nelson-haha.com/",
    "hal":"I'm sorry {0, but I'm afraid I can't do that.",
    "halflife":"3",
    "hammertime":"can't touch this",
    "helicopter":"dick",
    "helicopters":"dicks",
    "helpme":"Help me, {0}. You're my only hope.",
    "helpo":"okay",
    "hey":"(☞ﾟヮﾟ,☞ {0}",
    "hi":"!hi",
    "hl3":"CONFIRMED!!!",
    "hl4":"Ċ̨̈́̈̈́ͩ̇̔ͨ̓͌̒̓ͭ̐͒̑́҉̷̡̺̦͇̙̬͕͍͙̜̫͇̣O̧̡̩̣̟͛ͩ͒ͤ̒̒̏ͩ̉͊̊͠͡Ṋ̶̯̞̒͋ͭ̔̌̓ͭ̒̂̋̀͆̓ͦ̉ͫ̏̔̓͝͝͡͞ͅF̧̜̥͉͔̰̤̦͍̙͍̫̖̳͉̞̪ͨͩ͛͛͌͆ͪ̏͊͗̃͡Į̴̮̖͕͍̬̺̼̲̖̠̱̠͍̩͉̱̩̺̅͆ͤ͘R͓̳̮͍̬̝ͣ͂ͤͪ̑ͦ̂̒̈́̃̂̑̐͑ͨ̾̄̋̍͟M̦̹̤̣̣͇͈̫̒ͦ͗̍̇ͫ͌̇ͩͤ̈́̓͞͠E̸̹̭̗͕̜̖̺̭̹͇̳͍͂͐̎ͬ̐͑ͮ̓̑͊̄̏͌̓̚͞",
    "hodoripsum":"dtzitz is a pretty little princess",
    "holy":"HOLY SHIT IT'S A {0}!",
    "hope":"stfu",
    "html":"http://html9responsiveboilerstrapjs.com/",
    "hug":"/me sends {0} a big hug \0/",
    "hugtest":"{0} $nick",
    "huh":"{user}s",
    "hulk":"http://i.imgur.com/mXw0aXS.jpg",
    "human":"dont ya kno im hooman tooooooo",
    "hunter2":"See article here: http://www.bash.org/?244321",
    "i":"e",
    "id":"dtzitz is a pretty little princess",
    "idea":"dicks",
    "ideabot":"web interface",
    "idgaf":"https://www.youtube.com/watch?v=6wS5xOZ7Rq8",
    "ie":"dtzitz is a pretty little princess",
    "igotthis":"http://i.imgur.com/pGoWdO2.jpg",
    "ilikeprograms":"ilikeprograms likes all da programs",
    "important":"not important",
    "include":"<stdio.h>",
    "instagram":"http://bit.ly/1QPuxLe",
    "insult":"1, draw caricature of Muhammad 2, ????? 3, prophet",
    "integration":"WE FOLLOW \AGILE AS FUCK\METHODOLOGY. LOOK AT THIS, I JUST DRAGGED AND DROPPED INDEX.PHP INTO CUTE FTP. CONTINUOUS. FUCKING. INTEGRATION.",
    "internet":"The internet. Where the guys are guys, the women are guys, and little girls are Chris Hansen.",
    "intro":"html: http://learn.shayhowe.com/html-css/ layouts: http://learnlayout.com/",
    "invalid":"You're an invalid syntax!",
    "irrelevant":"http://i.imgur.com/8pW886e.jpg",
    "is":"phat",
    "j":"o",
    "jard":"!Jard",
    "jardayn":"<Jardayn> boo Tora",
    "jardayn-lives":"Latvia",
    "javascript":"pls",
    "jim":"http://i.imgflip.com/jt4sk.gif",
    "jive":"YOU A JIVE-ASS TURKAH, YA DIG {0}",
    "joins":"http://i.imgur.com/uvdJSa3.jpg",
    "joker":"Y SO SRS",
    "jones":"<veonik> literally jesus in a bottle",
    "jquery":"dtzitz is a pretty little princess",
    "js":"{0}.js",
    "jstherightway":"http://www.jstherightway.org/",
    "k":"n",
    "karamazov":"dtzitz is a pretty little princess",
    "kek":"saved",
    "kevrom":"<kevrom> I come pre-lubed",
    "kevrom1":"Please refrain from using !kevrom",
    "kevrom-lube":"<kevrom> I come pre-lubed",
    "kickballs":"/me swiftly kicks {0} in the balls",
    "kickem":"/kick {0}",
    "kickflip":"/me kickflips over {0}'s face, but biffs and hits {1} in the shin",
    "kicks":"/me sets mode +k on {0} on #/r/webdev.",
    "kike":"/me has kicked {0} (u r dum,",
    "killyourself":"I WANT TO BYE",
    "kittystyle":"KICK #/r/webdev omgwoo",
    "koala":"HOLY SHIT IT'S A KOALA!",
    "l":"i",
    "l@x":"http://media.giphy.com/media/114U4Pq1DFkvde/giphy.gif",
    "lang":"dtzitz is a pretty little princess",
    "laravel":"https://gist.github.com/anonymous/8565929",
    "laravel_guy":"jamesbdev is",
    "lax":"Lax_: fuck you",
    "lbp":"lololol",
    "left":"right",
    "lel":"dtzitz is a pretty little princess",
    "lennard":"(°͡ ʖ͜ °͡ ,",
    "lenny":"( ͡° ͜ʖ ͡°,",
    "letters":"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",
    "level":"IT'S OVER 9000!!!!!",
    "lightweight":"https://www.youtube.com/watch?v=-4m_9FFBHcg",
    "link":"http://i.imgur.com/PBkeX6f.jpg",
    "linode":"Linode (a portmanteau of the words linux and node, is a privately owned virtual private server provider based in Galloway, New Jersey. Linode offers multiple products and services for its clients.[1][3] Its flagship products are cloud-hosting services with multiple packages at different price points.[3] Linode Backup allows customers to backup their servers on a daily, weekly, or monthly basis.[3] Linode Ma",
    "litew8":"dicks",
    "lod":"ಠ_ಠ",
    "lodlol":"ಠ‿ಠ",
    "log":"lines of log is lol",
    "lol":"lol",
    "lolcoffy":"[16:08:20] <timeshifter> oh, you mean the coffy mug tray",
    "lolphp":"http://reddit.com/r/lolphp",
    "look":"/me points over there",
    "loop":"!loop",
    "lottoshares":"http://imgur.com/a/0W8kl",
    "lov":"Lovich: fuck you",
    "love":"is evol backward",
    "lovich":"Lovich is Love",
    "lovich2":"Lovich is Life",
    "lovichia":"children",
    "lp":"http://www.lemonparty.org",
    "m8":"mate",
    "malware":"http://imgur.com/JL1A94p",
    "mandelbrot":"https://dl.dropboxusercontent.com/u/7820717/html/mandelbrot.html",
    "mascot":"http://i.imgur.com/U6xI1Ln.jpg",
    "mash":"potatoes",
    "master":"/msg timeshifter What is your bidding, master?",
    "mate":"m8",
    "math":"It checks out.",
    "maths":"MATHSSSSS",
    "maxburn":"http://pokemon.wikia.com/wiki/Burn_Heal",
    "maybe":"Hey, I just met you, and this is crazy, but here's my number. So, call me maybe?",
    "mayweather":"https://www.youtube.com/watch?v=N4_mWhcfIh0",
    "mcfly":"Yes! Yes! I'm George McFly. I'm your density.",
    "meatwad":"http://i.imgur.com/olDObmu.jpg",
    "mecommand":"/me does an action",
    "meh":"http://i.imgur.com/6xsDO24.gifv",
    "meow":"It's like meowschwitz in there!",
    "meteor":"pls",
    "meth":"not even once.. except that one time",
    "method":"method for methoding methods into its own method",
    "miley":"NSFW http://www.yourtango.com/2013195617/celebrity-sex-miley-cyrus-hottest-nude-pics",
    "milf":"http://i.imgur.com/U4oLprv.png",
    "mindblown":"http://i.imgur.com/zaUJTTW.gifv",
    "mipadi":"<mipadi> i'm not on a Mac right now, though, so i don't know if i can really figure anything out",
    "mirrormirror":"mirror mirror on the wall, jamesbdev is the best of them all",
    "moist":"angrywombat's wife",
    "moist2":"and not cause of angrywombat",
    "monday":"black people.",
    "moose":"HOLY SHIT IT'S A MOOSE!",
    "most":"TIMEBOT MAKES ME MOIST",
    "motd":"MOTA IS LIKE WEED OR SOMETHING",
    "motivation":"Wow... My god! THIS IS AMAZING! I FEEL INCREDIBLE!!! YES! YES! YES! YES!! I FEEL GREAT! I CAN WIN! I. CAN. DO. THIS. ugh!... I'm home. I'm alive. This is all a miracle! I'm awake! I'M WIDE AWAKE! WHOOSH! ahahahahahahahaa",
    "mycock":"is much bigger than yours!",
    "n0":"no",
    "na":"x16",
    "nana":"x8",
    "nanana":"x5.3333333333333333333333333333333333333",
    "nananana":"x4",
    "nananananananananananananananana":"Batman!",
    "navy":"What the fuck did you just fucking say about me, you little bitch? I’ll have you know I graduated top of my class in the Navy Seals, and I’ve been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I’m the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the like",
    "naw":"bitch",
    "ncnsnr":"no-call no-show no-reference",
    "neat":"http://i.imgur.com/xlJq6Aa.jpg",
    "negateeev":"{-1}",
    "newcomputer":"http://www.bing.com/search?q={0}",
    "nice":"nice?",
    "nicetry":"Nice try, {0}.",
    "nick":"/me is now known as 04{0}",
    "nigga":"https://www.youtube.com/watch?v=G2zDW9me-IY",
    "niggers":"veonik timebot2 timeshifter dtzitz",
    "no":"N0",
    "noice":"http://i.imgur.com/P5U39N9.jpg",
    "noidea":"https://s-media-cache-ak0.pinimg.com/236x/99/95/fc/9995fc5ecf7abe34582a61c8205a295e.jpg",
    "noo":"http://www.nooooooooooooooo.com",
    "notbad":"http://i.imgur.com/q2kfvPk.jpg",
    "nou":"no u",
    "nsfw":"NSFW WARNING: {0}",
    "nt":"nt m8",
    "nuke":"/kick {0} this will never work out",
    "numbers":"123456789",
    "nun":"nunna yo biznez",
    "o m g":"Becky, look at her butt.",
    "o_o":"http://i.imgur.com/oiWBU94.jpg",
    "ohme":"http://i.imgur.com/MV25XdR.jpg",
    "ohpee":"is stick",
    "ohyou":"http://i.imgur.com/Bai2c.jpg",
    "oink":"http://www.veganpeace.com/animal_facts/Pictures/Pig4.jpg",
    "omfg":"tora",
    "omfgtora":"your butt is {0}",
    "omfgyoda":"Now, I see now... Blocked my socks5 proxy, my work seems to have. Hmmmmmm.",
    "omgmom":"your {0} is asleep",
    "omgpoo":"{prev}: your face is {0}",
    "omgwoo":"your face is {0}",
    "omgwooblog":"http://mypage.isasecret.com:52138",
    "once":"Once, I {0} a {1} all over this {2} and it made a giant {3} and {4}ed all over the place.",
    "onejob":"https://i.imgur.com/gz58GJz.gifv",
    "onionnion":"hataaaaaaa",
    "op":"{0}: https://www.youtube.com/watch?v=3RA4MykPm4s",
    "opme":"/mode #/r/webdev +o omgwoo",
    "ops":"{0}: https://www.youtube.com/watch?v=3RA4MykPm4s",
    "ostrich":"http://instantostrich.com/",
    "own":"saved",
    "oxford":"http://i.imgur.com/IyvXvpc.jpg",
    "packt":"https://www.packtpub.com/packt/offers/free-learning",
    "paddywhack":"http://imgur.com/gallery/tJTAw0w",
    "pakt":"https://www.packtpub.com/packt/offers/free-learning",


    "pants":"I'm not wearing any pants",
    "parse":"/me cheers",
    "party":"EVERYBODY DANCE NOW",
    "paste":"Please don't paste multiple lines directly into the channel. Instead use https://cryptbin.com to share code or text.",
    "pastebin":"GOD DAMN IT JARD USE A PASTEBIN",
    "pastethecodes":"Use cryptb.in to paste your code",
    "pedantic":"Here's your crown, bitch",
    "pen":"penetration",
    "penii":"omfgtora has many penii",
    "penis":"Sorry, all out. angrywombat is hogging them all to himself.",
    "penises":"#REF!",
    "pesto":"http://pastebin.com/ET5XAKSF",
    "pete":"!sandwichplz",
    "phony":"A BIG FAT PHONY",
    "php":"http://i.imgur.com/XnQoTdn.jpg",
    "php.sparrow":"dtzitz is a pretty little princess",
    "php.tool":"dtzitz is a pretty little princess",
    "php2":"http://phpthegoodparts.tumblr.com/",
    "phpdev":"PHP MASTER RACE",
    "phpnotbad":"dtzitz is a pretty little princess",
    "picard":"Tea, earl grey, hot.",
    "pie":"squishyj is a lie",
    "pilate":"Pilate",
    "ping":"pong",
    "pingas":"http://memecrunch.com/meme/38UE8/pingers/image.png?w=500&c=1",
    "pixlr":"http://apps.pixlr.com/editor/",
    "pizza":"Fuck papa johns. Their pizza sucks.",
    "pizzas":"Mmmm...",
    "planet":"With your powers combined: I am Captain Planet!",

    "players":".players",
    "plop":"plop plop fizz fizz oh what a relief it is!",
    "pls":"{prev}: fuck you",
    "police":"fuck tha",
    "pong":"donkey kong",
    "poo":"ask veonik.",
    "poop":"http://i.imgur.com/YJiET7i.jpg",
    "pop":"pop!",
    "popo":"All these squares make a circle.",
    "porn":"Yes, I do porn.",
    "pornsearch":"no siree, timeshifter won't allow it!",
    "potato":"tomato",
    "powaaaaa":"rangers!",
    "powah":"http://i.imgur.com/wcYHER2.gif",
    "pr0n":"I did omfgtora's mom",
    "pretzel":"/me roughly pokes his finger, ghoulishly sharpened nails and all, in omfgtora's asshole who is sharing a chocolate covered pretzel with {prev}",
    "prncs":"{prev}: I'm a princess!",
    "problem":"{0} you said you had a problem, not a hilarious problem.",
    "programmer":"<veonik> {0}: being a programmer makes programming not fun anymore",
    "programming":"http://threepanelsoul.com/2013/04/15/on-infinite-loops/",
    "project":"http://www.thesimplelogic.com/2015/01/15/the-blinking-cursor-how-do-you-start-a-project/",
    "promobin":"dtzitz is a pretty little princess",
    "prompt":"for dicks",
    "ps":"{user}: fuck you",
    "puddy1":"puddy1 | is a ragaholic someone addicted to period blood",
    "pultacat":"no",
    "pun":"That's punny",
    "pussy":"@cryptbin | a good clean pussy tastes more like skin to me",
    "putitback":"┬─┬ノ( º _ ºノ,",
    "pw":"{0}'s password is: *********",
    "pwnt":"OHH!! BITCH GOT PWNT!",
    "python":"ROOBY",
    "question":"dtzitz is a pretty little princess",
    "quill":"GODDAMN SIX LANES",
    "quitter":"/quit",
    "qweb":"{0}: Use /nick to change your name to something meaningful. You'll get more answers that way. Also, try !langhelp <language> to ping users who might be able to help you.",
    "rainbow":"4R7A8I9N12B6O13W",
    "ram":"downloadmoreram.com",
    "react":"pls",
    "readme":"dtzitz is a pretty little princess",
    "reallytold":"[ ] Not Told [X] Told [X] Really Told [X] TOLDASAURUS REX [X] Cash4Told.com [X] No Country for Told Men [X] Knights of the Told Republic [X] ToldSpice [x] The Elder Tolds IV: Oblivious [x] Command & Conquer: Toldberian Sun [x] GuiTold Hero: World Told [X] Told King of Boletaria [x] Countold Strike [x] Unreal Toldament [x] Stone-told Steve Austin [X] Half Life 2: Episode Told [X] Roller Coaster Toldcoon [x] Ass",
    "realpower":"https://youtu.be/X8ahCw4QwZY?t=1m4s",
    "recktim":"rectum? damn near killed 'im!",
    "rectum":"dtzitz is a pretty little princess",
    "recurse":"!recurse This is recursion!",
    "recursion":"http://i.imgur.com/GN0V4EY.gif",
    "reddit":".com",
    "reference":"http://i.imgur.com/4ycutyB.gif",
    "regex":"https://www.debuggex.com/",
    "rejard":"<angrywombat> what an r-tard <timeshifter> better than being a rejard <b14d3> Zing <timeshifter> whoops, did i type that out loud? <angrywombat> wait til Jardayn hears about this <angrywombat> you will rue the day <b14d3> Daddy wombat is going to tell on you <timeshifter> meh, i don't feel all that threatened by a potato",
    "rekt":"☐Not REKT ☐REKT ☑Tyrannosaurus REKT",
    "rekt2":"☐ Not REKT ☑ REKT ☑ REKTangle ☑ SHREKT ☑ REKT-it Ralph ☑ Total REKTall ☑ The Lord of the REKT ☑ The Usual SusREKTs ☑ North by NorthREKT ☑ REKT to the Future ☑ Once Upon a Time in the REKT ☑ The Good, the Bad, and the REKT ☑ LawREKT of Arabia ☑ Tyrannosaurus REKT ☑ eREKTile dysfunction",
    "rektlots":"shut the fuck up",
    "rektum":"dtzitz",
    "relax":"Lax Lax_: relax bruh",
    "repete":"!pete",
    "repost":"http://arstechnica.com/information-technology/2014/11/microsoft-open-sources-net-takes-it-to-linux-and-os-x/",
    "resettable":"{0} has been reset.",
    "restart":"Restarting...",
    "restoreops":"RESTORE OPS TO THE ONE TRUE GOD",
    "retard":"angrywombat dtzitz",
    "retards":"Users proficient in retard: Valeness",
    "rick":"♪ We're no strangers to love ♪ You know the rules and so. do. I ♪ A full commitment's what I'm thinkin' of ♪ You wouldn't get this from any other guy ♪ I-- just wanna tell you how I'm feelin' ♪ Gotta make you understand ♪ Never gonna give you up. Never gonna let you down. Never gonna run around and desert you ♪ Never gonna make you cry. Never gonna say goodbye. Never gonna tell a lie and hurt you ♪",
    "rickroll":"https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "right":"right",
    "right?":"right!",
    "rimshot":"Heyoooo!",
    "ring":"WRONG",
    "riot":"ヽ༼ຈل͜ຈ༽ﾉ {0} or riot ヽ༼ຈل͜ຈ༽ﾉ",
    "rms":"I'd just like to interject for a moment. What you’re referring to as Linux, is in fact, GNU/Linux, or as I’ve recently taken to calling it, GNU plus Linux. Linux is not an operating system unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising a full OS as defined by POSIX. Many computer users run a modified version of the",
    "robit":"death to all humans",
    "rolete":"http://www.urbandictionary.com/define.php?term=veonik",
    "roll":"bakery",
    "rolll":"they call me butter because I'm on a troll.",
    "roolet":"*BANG*",
    "roolette":"*BANG*",
    "rooski":"Jardayn | *heavy russian accent* Shifter has the oh pees, all jard abuse is allow to proceedings",
    "roulete":"/me has kicked {user} (because you're a fucking retard and can't type,",
    "rr":"https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "rtfm":"stfu timeshifter",
    "rude":"y u gotta b so r000000d",
    "rulette":"*BANG*",
    "russianroulette":"dtzitz is a pretty little princess",
    "sad":"(ಥ_ಥ,",
    "saila":"!alias add test test",
    "sɐıʃɐ¡":"alias!",
    "salty":"http://i.imgur.com/2EoqTNN.jpg",
    "same":"dtzitz is a pretty little princess",
    "sandwich":"Make your own sandwich.",
    "sandwichplz":"Here is your sandwich sir.",
    "sap":"dtzitz is a pretty little princess",
    "sarc":"ITT: Jardayn can't detect sarcasm",
    "saturday":"https://www.youtube.com/watch?v=GVCzdpagXOQ",
    "say":"{0}",
    "scriptor":"go away",
    "sed":"I don't parse myself so tricks like s/I/!trivia/ won't work.",
    "set":"Use !alias add [term] [definition], you retard.",
    "shame":"<Dragory> SHAME ding",
    "sharepoint":"dtzitz is a pretty little princess",
    "shark":"I'm a shark! I'm a shark! Suck my dick, I'm a shark!",
    "shart":"/me sharts on {prev}",
    "shia":"http://youtu.be/o0u4M6vppCI",
    "shifter":"TIMESHIFTER",
    "shit":"/me takes a steaming shit on {0}",
    "shoot":"/me shoots down {0} with a barrage of bullets",
    "shotsfired":"(∩ ͡° ͜ʖ ͡°,⊃━☆ﾟ. * ･ ｡ﾟ pew pew pew",
    "shutdown":"The system is going down to maintenance mode NOW!",
    "sideeye":"http://i.imgur.com/WBTJ1Ta.jpg",
    "sig":"<sig> you'll get much deeper just by doing it",
    "skylines":"*timeshifter spreadsheets all over the place*",
    "slap":"/me slaps {0} with a big smelly trout",
    "slapwith":"/me slaps {0} with {1} {2} {3} {4} {5}",
    "smash":"/me smashes omfgtora's face with {user}'s detached arm",
    "smoke":"vape",
    "snap":"dtzitz is a pretty little princess",
    "somad":"teslanick is so mad",
    "something":"meh",
    "sortcss":"https://github.com/AndreasBackx/StyleSorter",
    "spaceballz":"awesome",
    "spam":"dtzitz is a pretty little princess",
    "spambot":"/me points to self",
    "spammer":"timeshifter",
    "sql":"http://sol.gfxile.net/g3/",
    "sqljoin":"http://blog.codinghorror.com/a-visual-explanation-of-sql-joins/",
    "squeal":"You got a purdy mouf",
    "stab":"/me stabs {0} with a herring.",
    "startdancing":"/me dances around the room",
    "startrek":"shit",
    "starwars":"shit",
    "stick":"is timebot2",
    "stirfriday":"dtzitz is a pretty little princess",
    "stoned":"http://pastebin.com/ccE87MVT",
    "stuck":"http://blog.thefirehoseproject.com/posts/learn-to-code-and-be-self-reliant/",
    "su":"Password:",
    "suckdicks":"<{0}> I suck dicks.",
    "sudo":"Password:",
    "sug":"http://vignette2.wikia.nocookie.net/kingofthehill/images/a/ad/Nancy_2.jpg",
    "suicide":"BOOM!",
    "sunglasses":"(•_•, ( •_•,>⌐■-■ (⌐■_■,",
    "sup":"http://i.imgur.com/f1DHjIE.gif",
    "surak":"SUUUUUUURAAAAAAAAAAK",
    "suspense":"http://media.giphy.com/media/kKdgdeuO2M08M/giphy.gif",
    "swagger":"https://www.youtube.com/watch?v=PovbPwRsdo0",
    "swine":"{0} is such a dimwitted swine",
    "syntax":"Invalid syntax.",
    "tacky":"https://www.youtube.com/watch?v=zq7Eki5EZ8o",
    "tb":"/me has aids",
    "tbh":"/me has {0}",
    "technically":"http://xkcd.org/1475/",
    "techsupport":"http://i.imgur.com/S8mYnWq.png",
    "tesla":"I'M PUSHING AGAINST THE ENTROPY, BUT THE KNITTED CASTLE GROWS http://i.imgur.com/VuNPlRt.png",
    "teslanick":"http://i.imgur.com/iAQil.jpg",
    "test":"test",
    "test2":"\x01 ACTION tests\x01",
    "test3 test4":"test5",
    "testhi":"Hi, {user}!",
    "testhi2":"{user{user}}",
    "tfs":"teamfourstar.com",
    "tgif2":"https://www.youtube.com/watch?v=GVCzdpagXOQ",
    "the_monkey":"dtzitz is a pretty little princess",
    "themesong":"/me sings omfgtora's themesong: NanaNanaNana NanaNanaNana NANA TORA!",
    "thing":"This {0} right here nigga?",
    "this":"this is undefined",
    "thismanisawhore":"who is timeshifter?",
    "thursday":"one more day then it's party time",
    "timbot":"<+angrywombat> fuck you timbot",
    "time":"fuck this bot",
    "timebot":"http://i.imgur.com/WsyFSnZ.jpg",
    "timebot2":"The bot the channel deserves, just not the one that it needs right now.",
    "timebot3":"confirmed",
    "timeshifta":"shiftin time",
    "timeshifter":"http://jsfiddle.net/oa0tLvwa/",
    "timeshifter1":"!timeshifter1",
    "timeshifteris":"a cunt",
    "timeshitter":"Lovich: fuck you",
    "timeshittertimeshifter>":"hey, would you mess with a guy who can remotely shut your computer down while you're trying to finish an essay that's due today? ---> http://i.imgur.com/wCScgcL.gif",
    "timewasted":"too fucking much",
    "tinglyasshole":"timeshifter",
    "tip":"/me tips fedora at {user}",
    "tir":"no.",
    "tit":"what's twisting this bitch's tit?",
    "tits":"boobs",
    "tmc":"Too Many Cooks ♫",
    "told":"dtzitz is a pretty little princess",
    "toomanycocks":"Too Many Cocks ♫",
    "toomanycooks":"Too Many Cooks ♫",
    "toot":"toot toot mother fuckers!",
    "topkek":"saved",
    "tora":"NSFW: http://i.imgur.com/IvGBaR5.gif",
    "torasux":"test {time}",
    "towel":"don't forget to bring your towel",
    "tramapoline":"https://www.youtube.com/watch?v=geHqnV4Mk_4",
    "trash":"/me unleashes the fury in {0}'s house, wrecking the place",
    "trawl":"TROLL DETECTED {0}",
    "trigger":"{0} is one of my triggers.",
    "trivia":"it's over!",
    "trollface":"http://i.imgur.com/1CDAI.jpg",
    "trolljs":"/join #javascript",
    "trollsjs":"dtzitz is a pretty little princess",
    "trout":"/me sends a smelly trout {0}'s way, courtesy of {user} (it came from {user}'s butt,.",
    "truth":"dats da troof",
    "ts":"-timeshifter | every time i hear that name i think of deep space 9",
    "tstest":"thing! {0:C}",
    "ttj":"thatsthejoke.jpg",
    "tubbro":"saved",
    "tuesday":"white people.",
    "turb0":"<turb0> I LOVE ME SOME COCK IN MY MOUTH",
    "turb1":"Err: list index out of range",
    "turbro":"bro",
    "turkey":"cheddar",
    "typescript":"pls",
    "tyrone":"get your shit together {0}",
    "u wot m8":"!uwot",
    "ubergm":"You ebola-infested drunk teen mom!",
    "umad":"teslanick is mad",
    "uncss":"http://davidwalsh.name/uncss",
    "unshartable":"exclamation = protection",
    "urmom":"ಠ‿ಠ",
    "uwotfight":"(ง'̀-'́,ง",
    "uwotmate":"https://soundcloud.com/totalbiscuit/our-official-stance-on-kotaku-uks-potentially-libellous-tweet",
    "v":"V: Voilà! In view, a humble vaudevillian veteran cast vicariously as both victim and villain by the vicissitudes of Fate. This visage, no mere veneer of vanity, is a vestige of the vox populi, now vacant, vanished. However, this valourous visitation of a bygone vexation stands vivified and has vowed to vanquish these venal and virulent",
    "val":"dammit",
    "valeness":"i dont even",
    "valeness2":"I fucked a fish once",
    "vaminos":"Everybody let's go!",
    "vape":"smoke",
    "vaporise":"its a z, faggot",
    "vaporize":"shutup Lovich",
    "vb":"guis for days",
    "veonik":"penis!",
    "veonik2":"I AM LEET SCRUB",
    "veonikzane":"zane get web for veonik",
    "vidya":"gamez",
    "visualbasic":"dicks",
    "voiceme":":<test> /mode #/r/webdev +v {0}",
    "vulcan":"live long n prosper bitchez",
    "w8":"wait",
    "wat":"http://i.imgur.com/0CQZw4z.jpg",
    "wdkevin":"Master and Commander",
    "website":"http://motherfuckingwebsite.com/",
    "ween":"{prev}: weenises are my specialty",
    "weird":"{0{0}} is weird",
    "what":"OHHHHHHHHHHKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY",
    "whatever":"¯\\_(ツ,_/¯",
    "whilst":"{0}: The word is \"while\" you pretentious douche.",
    "whisperme":"/PRIVMSG omgwoo whee",
    "whitelist":"{0}: But for why?",
    "whore":"I'm a dirty whore!",
    "why":"BECAUSE FUCK YOU! THAT'S WHY!",
    "whypython":"<kevrom> and if someone can't bother to learn friggin' python to maintain something i write they don't deserve to work behind me",
    "witlf":"What\nIn\n\The\nLiteral\nFuck",

    "wizard":"http://i.imgur.com/jPVcloU.gif",
    "wombocom":"lemonparty.org",
    "wrecked":"☐Not REKT ☐REKT ☑REKT-it Ralph",
    "wrong":"its always wrong",
    "wtf":"http://i.imgur.com/igPDqtG.gif",
    "wut":"Has Anyone Really Been Far Even as Decided to Use Even Go Want to do Look More Like?",
    "yahoo":"FUCK I AM USELESS",
    "yay":"http://i.imgur.com/5SAehRX.jpg",
    "yeah":"yeah",
    "yeahyeah":"http://i.imgur.com/nW55YP2.jpg",
    "yes":"yissssss",
    "yoink":"http://i.imgur.com/mRRFjp7.gif",
    "yolo":"swag",
    "yourethemannowdog":"http://yourethemannowdog.ytmnd.com/",
    "youthinkitsfunny":"You think it's funny {0}?",
    "zalgo":"H̿҉̳̥͉͉͖̺̟e̳͉͉͑ͨ́̀̅͐̏ͤ̿͟͟͠ ̶̟̜̜͇̣̲͇͖̄ͤ̾w̤̺̐͆͆̓̔ͣh̦̭͉ͬ́̓͒̄̔͊̎͜ǫ̧̜͎͛͌ͪ̚ ̨̧͔̤͋ͤW̓҉̗a͊ͮ͂҉̨̤̥͖̤̰̳̲̀i̸͔̯̠̗̿̀́t͔̘͉͂͂ͥ͒͌̕̕s͙̻͈̟̠͗̈́̿̊̀ͮ̿̃ͪ͡ͅ ̴̻̭̠̼͖̈́B̼̰͕̝̪̪͙̰̣ͧ̎͢e̛͈͚̻͚͔̙̲̲ͥ́ͮ̀̈͞h̸͕̺͎̦͇̼̟͓̋̃ͪͦ͛͐͗ͨ͞į̤̩̌̓ͭͭͬͦ͘ṋ̃̒d̢̖͉̪͍̮̙͔̄̀ ͍͒̉",
    "zane":"zane get web",
    "zanegort":"zanegort: shrug if you're useless",
    "zen":"https://www.youtube.com/watch?v=4TyGik21kK4",
    "zoid":"zoid?",
    "zoidberg":"(\\/, (°,,,°, (\\/, WOOOOPWOPWOPWOPWOP",
    "zombo":"zombo.com",
    "zombocom":"zombo.com",
    "💩":":D",
    "出伊久":"fuck you richard,",
    "hotedit":"oh cool"
  }
}
